version: 0.0
os: linux
files: 
  - 
    destination: /var/lib/tomcat/webapps
    source: /gameoflife-web/target/
hooks:
  BeforeInstall:
    - location: Scripts/stop.sh
  AfterInstall:
    - location: Scripts/start.sh
