version: 0.0
os: linux
files: 
  - 
    destination: /var/lib/tomcat/webapps 
    source: /gameoflife-web/target/
hooks:
  BeforeInstall:
    - location: stop.sh
  AfterInstall:
    - location: start.sh
